name: RunScript
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: checkout directory
      run: checkout QA-Work
  
    - name: run script
      run: script.sh
