name: RunScript
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    steps:
      - name: run script
        run: bash ./script.sh
